web: gunicorn config.wsgi --workers 4 --worker-class gthread --threads 2 --bind 0.0.0.0:$PORT --log-level=info
worker: celery -A config worker --loglevel=info --concurrency=4
beat: celery -A config beat --loglevel=info
